# Generated by Django 4.2.5 on 2023-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="会社名"),
                ),
                ("sales_yoy", models.FloatField(null=True, verbose_name="売上高3年平均")),
                (
                    "operating_income",
                    models.FloatField(null=True, verbose_name="営業利益3年平均"),
                ),
                ("roe", models.FloatField(null=True, verbose_name="ROE")),
                ("粗利率", models.FloatField(null=True, verbose_name="粗利率")),
                ("有形固定資産", models.FloatField(null=True, verbose_name="有形固定資産")),
                ("固定負債", models.FloatField(null=True, verbose_name="固定負債")),
                ("自己資本比率", models.FloatField(null=True, verbose_name="自己資本比率")),
                ("per", models.FloatField(null=True, verbose_name="per")),
                ("pbr", models.FloatField(null=True, verbose_name="pbr")),
                ("業種", models.CharField(max_length=100, null=True, verbose_name="業種")),
                ("海外売上高比率", models.FloatField(null=True, verbose_name="海外売上高比率")),
            ],
        ),
    ]
