# Generated by Django 4.2.5 on 2023-12-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
