# Generated by Django 4.2.5 on 2024-01-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="海外売上高比率",
        ),
        migrations.AddField(
            model_name="company",
            name="上場年数",
            field=models.FloatField(blank=True, null=True, verbose_name="上場年数"),
        ),
        migrations.AddField(
            model_name="company",
            name="人件費_純利益",
            field=models.FloatField(blank=True, null=True, verbose_name="純利益に占める販管費"),
        ),
        migrations.AddField(
            model_name="company",
            name="取締役報酬",
            field=models.FloatField(blank=True, null=True, verbose_name="取締役報酬"),
        ),
        migrations.AddField(
            model_name="company",
            name="従業員一人当たりの売上",
            field=models.FloatField(blank=True, null=True, verbose_name="従業員一人当たりの売上"),
        ),
        migrations.AddField(
            model_name="company",
            name="流動比率",
            field=models.FloatField(blank=True, null=True, verbose_name="流動比率"),
        ),
        migrations.AddField(
            model_name="company",
            name="研究開発売上比率",
            field=models.FloatField(blank=True, null=True, verbose_name="研究開発売上比率"),
        ),
        migrations.AddField(
            model_name="company",
            name="賞与引当金_従業員数",
            field=models.FloatField(
                blank=True, null=True, verbose_name="従業員一人当たりの賞与引当金"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="退職給付引当金_従業員数",
            field=models.FloatField(
                blank=True, null=True, verbose_name="従業員一人あたりの退職給付引当金"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="cluster",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "クラスター0"), (1, "クラスター1"), (2, "クラスター2"), (3, "クラスター3")],
                null=True,
                verbose_name="クラスター",
            ),
        ),
    ]
