# Generated by Django 4.2.5 on 2023-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="会社名",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="operating_income",
            new_name="営業利益",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="sales_yoy",
            new_name="売上高",
        ),
        migrations.AddField(
            model_name="company",
            name="株価上昇率",
            field=models.FloatField(null=True, verbose_name="3年の株価上昇率"),
        ),
    ]
