# Generated by Django 4.2.5 on 2023-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_rename_name_company_会社名_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="会社ロゴ",
            field=models.ImageField(
                null=True, upload_to="company", verbose_name="会社ロゴ"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="勤続年数",
            field=models.FloatField(default=1, verbose_name="勤続年数"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="平均年収",
            field=models.FloatField(null=True, verbose_name="平均年収"),
        ),
        migrations.AddField(
            model_name="company",
            name="平均年齢",
            field=models.FloatField(null=True, verbose_name="平均年齢"),
        ),
        migrations.AddField(
            model_name="company",
            name="従業員数",
            field=models.FloatField(null=True, verbose_name="従業員数"),
        ),
        migrations.AddField(
            model_name="company",
            name="持ち株",
            field=models.CharField(default=1, max_length=100, verbose_name="持ち株"),
            preserve_default=False,
        ),
    ]
