# Generated by Django 4.2.5 on 2024-01-28 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_company_cluster_alter_company_industry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="賞与引当金_従業員数",
        ),
        migrations.RemoveField(
            model_name="company",
            name="退職給付引当金_従業員数",
        ),
    ]
