# Generated by Django 4.2.5 on 2024-01-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_remove_company_賞与引当金_従業員数_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="上場年数",
            field=models.IntegerField(blank=True, null=True, verbose_name="上場年数"),
        ),
    ]
