# Generated by Django 4.2.5 on 2023-12-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_alter_company_業種"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
