# Generated by Django 4.2.5 on 2024-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_company_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="cluster",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "平均的な会社"),
                    (1, "建物を大量に保有"),
                    (2, "利益成長バケモノ"),
                    (3, "出来杉くん(優秀)"),
                ],
                null=True,
                verbose_name="クラスター",
            ),
        ),
    ]
