# Generated by Django 4.2.5 on 2023-12-24 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0009_company_事業内容_alter_company_業種"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="業種",
            new_name="industry",
        ),
    ]
