# Generated by Django 4.2.5 on 2023-12-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0012_alter_company_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="従業員数",
            field=models.IntegerField(null=True, verbose_name="従業員数"),
        ),
    ]
