# Generated by Django 4.2.5 on 2023-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0013_alter_company_従業員数"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="平均年収",
            field=models.IntegerField(null=True, verbose_name="平均年収"),
        ),
    ]
