# Generated by Django 4.2.5 on 2024-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0014_alter_company_平均年収"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="取締役",
            field=models.FloatField(null=True, verbose_name="報酬"),
        ),
        migrations.AddField(
            model_name="company",
            name="社外役員",
            field=models.FloatField(null=True, verbose_name="報酬"),
        ),
    ]
