# Generated by Django 4.2.5 on 2024-01-02 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0016_rename_社外役員_company_それ以外の取締役"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="それ以外の取締役",
            new_name="社外役員",
        ),
    ]
