# Generated by Django 4.2.5 on 2024-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0017_rename_それ以外の取締役_company_社外役員"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="社外役員",
            field=models.IntegerField(null=True, verbose_name="報酬"),
        ),
    ]
