# Generated by Django 4.2.5 on 2024-01-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0018_alter_company_社外役員"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="取締役",
        ),
        migrations.RemoveField(
            model_name="company",
            name="社外役員",
        ),
        migrations.AddField(
            model_name="company",
            name="取締役_報酬",
            field=models.FloatField(null=True, verbose_name="取締役_報酬"),
        ),
        migrations.AddField(
            model_name="company",
            name="社外役員_報酬",
            field=models.IntegerField(null=True, verbose_name="社外役員_報酬"),
        ),
    ]
