# Generated by Django 4.2.5 on 2024-01-02 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0019_remove_company_取締役_remove_company_社外役員_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="社外役員_報酬",
        ),
    ]
