# Generated by Django 4.2.5 on 2024-01-02 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0020_remove_company_社外役員_報酬"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="取締役_報酬",
            new_name="取締役報酬",
        ),
    ]
