# Generated by Django 4.2.5 on 2024-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0021_rename_取締役_報酬_company_取締役報酬"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="取締役報酬",
            field=models.IntegerField(null=True, verbose_name="取締役_報酬"),
        ),
    ]
